/* Generated by DBCC, see <https://github.com/howerj/dbcc> 
This file was generated by dbcc: See <https://github.com/howerj/dbcc>

Consider donating; see the repo for more information, this project 
requires your support to continue.

For those with paid support or to inquire about paid support
please Email <mailto:hello.operator.co.uk@gmail.com>.

*/

#include "Megasquirt_simplified_dash_broadcast.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x5e8_megasquirt_dash0(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* map: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5e8_megasquirt_dash0.map)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* rpm: start-bit 23, length 16, endianess motorola, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x5e8_megasquirt_dash0.rpm)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* clt: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5e8_megasquirt_dash0.clt)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* tps: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5e8_megasquirt_dash0.tps)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x5e8_megasquirt_dash0_tx = 1;
	return 8;
}

static int unpack_can_0x5e8_megasquirt_dash0(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* map: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x5e8_megasquirt_dash0.map = x;
	/* rpm: start-bit 23, length 16, endianess motorola, scaling 1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x5e8_megasquirt_dash0.rpm = x;
	/* clt: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x5e8_megasquirt_dash0.clt = x;
	/* tps: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = m & 0xffff;
	o->can_0x5e8_megasquirt_dash0.tps = x;
	o->can_0x5e8_megasquirt_dash0_rx = 1;
	o->can_0x5e8_megasquirt_dash0_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x5e8_map(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e8_megasquirt_dash0.map);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5e8_map(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5e8_megasquirt_dash0.map = in;
	return 0;
}

int decode_can_0x5e8_rpm(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x5e8_megasquirt_dash0.rpm);
	*out = rval;
	return 0;
}

int encode_can_0x5e8_rpm(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x5e8_megasquirt_dash0.rpm = in;
	return 0;
}

int decode_can_0x5e8_clt(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e8_megasquirt_dash0.clt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5e8_clt(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5e8_megasquirt_dash0.clt = in;
	return 0;
}

int decode_can_0x5e8_tps(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e8_megasquirt_dash0.tps);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5e8_tps(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5e8_megasquirt_dash0.tps = in;
	return 0;
}

int print_can_0x5e8_megasquirt_dash0(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "map = (wire: %.0f)\n", (double)(o->can_0x5e8_megasquirt_dash0.map)));
	r = print_helper(r, fprintf(output, "rpm = (wire: %.0f)\n", (double)(o->can_0x5e8_megasquirt_dash0.rpm)));
	r = print_helper(r, fprintf(output, "clt = (wire: %.0f)\n", (double)(o->can_0x5e8_megasquirt_dash0.clt)));
	r = print_helper(r, fprintf(output, "tps = (wire: %.0f)\n", (double)(o->can_0x5e8_megasquirt_dash0.tps)));
	return r;
}

static int pack_can_0x5e9_megasquirt_dash1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* pw1: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x5e9_megasquirt_dash1.pw1)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* pw2: start-bit 23, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x5e9_megasquirt_dash1.pw2)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* mat: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5e9_megasquirt_dash1.mat)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* adv_deg: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5e9_megasquirt_dash1.adv_deg)) & 0xffff;
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x5e9_megasquirt_dash1_tx = 1;
	return 8;
}

static int unpack_can_0x5e9_megasquirt_dash1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* pw1: start-bit 7, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x5e9_megasquirt_dash1.pw1 = x;
	/* pw2: start-bit 23, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x5e9_megasquirt_dash1.pw2 = x;
	/* mat: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x5e9_megasquirt_dash1.mat = x;
	/* adv_deg: start-bit 55, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = m & 0xffff;
	o->can_0x5e9_megasquirt_dash1.adv_deg = x;
	o->can_0x5e9_megasquirt_dash1_rx = 1;
	o->can_0x5e9_megasquirt_dash1_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x5e9_pw1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e9_megasquirt_dash1.pw1);
	rval *= 0.001;
	*out = rval;
	return 0;
}

int encode_can_0x5e9_pw1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 1000;
	o->can_0x5e9_megasquirt_dash1.pw1 = in;
	return 0;
}

int decode_can_0x5e9_pw2(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e9_megasquirt_dash1.pw2);
	rval *= 0.001;
	*out = rval;
	return 0;
}

int encode_can_0x5e9_pw2(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 1000;
	o->can_0x5e9_megasquirt_dash1.pw2 = in;
	return 0;
}

int decode_can_0x5e9_mat(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e9_megasquirt_dash1.mat);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5e9_mat(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5e9_megasquirt_dash1.mat = in;
	return 0;
}

int decode_can_0x5e9_adv_deg(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5e9_megasquirt_dash1.adv_deg);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5e9_adv_deg(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5e9_megasquirt_dash1.adv_deg = in;
	return 0;
}

int print_can_0x5e9_megasquirt_dash1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "pw1 = (wire: %.0f)\n", (double)(o->can_0x5e9_megasquirt_dash1.pw1)));
	r = print_helper(r, fprintf(output, "pw2 = (wire: %.0f)\n", (double)(o->can_0x5e9_megasquirt_dash1.pw2)));
	r = print_helper(r, fprintf(output, "mat = (wire: %.0f)\n", (double)(o->can_0x5e9_megasquirt_dash1.mat)));
	r = print_helper(r, fprintf(output, "adv_deg = (wire: %.0f)\n", (double)(o->can_0x5e9_megasquirt_dash1.adv_deg)));
	return r;
}

static int pack_can_0x5ea_megasquirt_dash2(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* egocor1: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5ea_megasquirt_dash2.egocor1)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* egt1: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5ea_megasquirt_dash2.egt1)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* pwseq1: start-bit 55, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = ((uint16_t)(o->can_0x5ea_megasquirt_dash2.pwseq1)) & 0xffff;
	m |= x;
	/* afrtgt1: start-bit 7, length 8, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint8_t)(o->can_0x5ea_megasquirt_dash2.afrtgt1)) & 0xff;
	x <<= 56; 
	m |= x;
	/* AFR1: start-bit 15, length 8, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint8_t)(o->can_0x5ea_megasquirt_dash2.AFR1)) & 0xff;
	x <<= 48; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x5ea_megasquirt_dash2_tx = 1;
	return 8;
}

static int unpack_can_0x5ea_megasquirt_dash2(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* egocor1: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x5ea_megasquirt_dash2.egocor1 = x;
	/* egt1: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x5ea_megasquirt_dash2.egt1 = x;
	/* pwseq1: start-bit 55, length 16, endianess motorola, scaling 0.001, offset 0 */
	x = m & 0xffff;
	o->can_0x5ea_megasquirt_dash2.pwseq1 = x;
	/* afrtgt1: start-bit 7, length 8, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 56) & 0xff;
	o->can_0x5ea_megasquirt_dash2.afrtgt1 = x;
	/* AFR1: start-bit 15, length 8, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xff;
	o->can_0x5ea_megasquirt_dash2.AFR1 = x;
	o->can_0x5ea_megasquirt_dash2_rx = 1;
	o->can_0x5ea_megasquirt_dash2_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x5ea_egocor1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ea_megasquirt_dash2.egocor1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ea_egocor1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ea_megasquirt_dash2.egocor1 = in;
	return 0;
}

int decode_can_0x5ea_egt1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ea_megasquirt_dash2.egt1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ea_egt1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ea_megasquirt_dash2.egt1 = in;
	return 0;
}

int decode_can_0x5ea_pwseq1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ea_megasquirt_dash2.pwseq1);
	rval *= 0.001;
	*out = rval;
	return 0;
}

int encode_can_0x5ea_pwseq1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 1000;
	o->can_0x5ea_megasquirt_dash2.pwseq1 = in;
	return 0;
}

int decode_can_0x5ea_afrtgt1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ea_megasquirt_dash2.afrtgt1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ea_afrtgt1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ea_megasquirt_dash2.afrtgt1 = in;
	return 0;
}

int decode_can_0x5ea_AFR1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ea_megasquirt_dash2.AFR1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ea_AFR1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ea_megasquirt_dash2.AFR1 = in;
	return 0;
}

int print_can_0x5ea_megasquirt_dash2(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "egocor1 = (wire: %.0f)\n", (double)(o->can_0x5ea_megasquirt_dash2.egocor1)));
	r = print_helper(r, fprintf(output, "egt1 = (wire: %.0f)\n", (double)(o->can_0x5ea_megasquirt_dash2.egt1)));
	r = print_helper(r, fprintf(output, "pwseq1 = (wire: %.0f)\n", (double)(o->can_0x5ea_megasquirt_dash2.pwseq1)));
	r = print_helper(r, fprintf(output, "afrtgt1 = (wire: %.0f)\n", (double)(o->can_0x5ea_megasquirt_dash2.afrtgt1)));
	r = print_helper(r, fprintf(output, "AFR1 = (wire: %.0f)\n", (double)(o->can_0x5ea_megasquirt_dash2.AFR1)));
	return r;
}

static int pack_can_0x5eb_megasquirt_dash3(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* batt: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5eb_megasquirt_dash3.batt)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* sensors1: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x5eb_megasquirt_dash3.sensors1)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* sensors2: start-bit 39, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x5eb_megasquirt_dash3.sensors2)) & 0xffff;
	x <<= 16; 
	m |= x;
	/* knk_rtd: start-bit 55, length 8, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint8_t)(o->can_0x5eb_megasquirt_dash3.knk_rtd)) & 0xff;
	x <<= 8; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x5eb_megasquirt_dash3_tx = 1;
	return 8;
}

static int unpack_can_0x5eb_megasquirt_dash3(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* batt: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x5eb_megasquirt_dash3.batt = x;
	/* sensors1: start-bit 23, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x5eb_megasquirt_dash3.sensors1 = x;
	/* sensors2: start-bit 39, length 16, endianess motorola, scaling 0.01, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x5eb_megasquirt_dash3.sensors2 = x;
	/* knk_rtd: start-bit 55, length 8, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 8) & 0xff;
	o->can_0x5eb_megasquirt_dash3.knk_rtd = x;
	o->can_0x5eb_megasquirt_dash3_rx = 1;
	o->can_0x5eb_megasquirt_dash3_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x5eb_batt(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5eb_megasquirt_dash3.batt);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5eb_batt(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5eb_megasquirt_dash3.batt = in;
	return 0;
}

int decode_can_0x5eb_sensors1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5eb_megasquirt_dash3.sensors1);
	rval *= 0.01;
	*out = rval;
	return 0;
}

int encode_can_0x5eb_sensors1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 100;
	o->can_0x5eb_megasquirt_dash3.sensors1 = in;
	return 0;
}

int decode_can_0x5eb_sensors2(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5eb_megasquirt_dash3.sensors2);
	rval *= 0.01;
	*out = rval;
	return 0;
}

int encode_can_0x5eb_sensors2(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 100;
	o->can_0x5eb_megasquirt_dash3.sensors2 = in;
	return 0;
}

int decode_can_0x5eb_knk_rtd(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5eb_megasquirt_dash3.knk_rtd);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5eb_knk_rtd(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5eb_megasquirt_dash3.knk_rtd = in;
	return 0;
}

int print_can_0x5eb_megasquirt_dash3(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "batt = (wire: %.0f)\n", (double)(o->can_0x5eb_megasquirt_dash3.batt)));
	r = print_helper(r, fprintf(output, "sensors1 = (wire: %.0f)\n", (double)(o->can_0x5eb_megasquirt_dash3.sensors1)));
	r = print_helper(r, fprintf(output, "sensors2 = (wire: %.0f)\n", (double)(o->can_0x5eb_megasquirt_dash3.sensors2)));
	r = print_helper(r, fprintf(output, "knk_rtd = (wire: %.0f)\n", (double)(o->can_0x5eb_megasquirt_dash3.knk_rtd)));
	return r;
}

static int pack_can_0x5ec_megasquirt_dash4(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t m = 0;
	/* VSS1: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5ec_megasquirt_dash4.VSS1)) & 0xffff;
	x <<= 48; 
	m |= x;
	/* tc_retard: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5ec_megasquirt_dash4.tc_retard)) & 0xffff;
	x <<= 32; 
	m |= x;
	/* launch_timing: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x5ec_megasquirt_dash4.launch_timing)) & 0xffff;
	x <<= 16; 
	m |= x;
	*data = reverse_byte_order(m);
	o->can_0x5ec_megasquirt_dash4_tx = 1;
	return 8;
}

static int unpack_can_0x5ec_megasquirt_dash4(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t m = reverse_byte_order(data);
	if (dlc < 8)
		return -1;
	/* VSS1: start-bit 7, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 48) & 0xffff;
	o->can_0x5ec_megasquirt_dash4.VSS1 = x;
	/* tc_retard: start-bit 23, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 32) & 0xffff;
	o->can_0x5ec_megasquirt_dash4.tc_retard = x;
	/* launch_timing: start-bit 39, length 16, endianess motorola, scaling 0.1, offset 0 */
	x = (m >> 16) & 0xffff;
	o->can_0x5ec_megasquirt_dash4.launch_timing = x;
	o->can_0x5ec_megasquirt_dash4_rx = 1;
	o->can_0x5ec_megasquirt_dash4_time_stamp_rx = time_stamp;
	return 8;
}

int decode_can_0x5ec_VSS1(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ec_megasquirt_dash4.VSS1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ec_VSS1(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ec_megasquirt_dash4.VSS1 = in;
	return 0;
}

int decode_can_0x5ec_tc_retard(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ec_megasquirt_dash4.tc_retard);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ec_tc_retard(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ec_megasquirt_dash4.tc_retard = in;
	return 0;
}

int decode_can_0x5ec_launch_timing(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x5ec_megasquirt_dash4.launch_timing);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x5ec_launch_timing(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x5ec_megasquirt_dash4.launch_timing = in;
	return 0;
}

int print_can_0x5ec_megasquirt_dash4(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "VSS1 = (wire: %.0f)\n", (double)(o->can_0x5ec_megasquirt_dash4.VSS1)));
	r = print_helper(r, fprintf(output, "tc_retard = (wire: %.0f)\n", (double)(o->can_0x5ec_megasquirt_dash4.tc_retard)));
	r = print_helper(r, fprintf(output, "launch_timing = (wire: %.0f)\n", (double)(o->can_0x5ec_megasquirt_dash4.launch_timing)));
	return r;
}

int unpack_message(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x5e8: return unpack_can_0x5e8_megasquirt_dash0(o, data, dlc, time_stamp);
	case 0x5e9: return unpack_can_0x5e9_megasquirt_dash1(o, data, dlc, time_stamp);
	case 0x5ea: return unpack_can_0x5ea_megasquirt_dash2(o, data, dlc, time_stamp);
	case 0x5eb: return unpack_can_0x5eb_megasquirt_dash3(o, data, dlc, time_stamp);
	case 0x5ec: return unpack_can_0x5ec_megasquirt_dash4(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_megasquirt_simplified_dash_broadcast_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x5e8: return pack_can_0x5e8_megasquirt_dash0(o, data);
	case 0x5e9: return pack_can_0x5e9_megasquirt_dash1(o, data);
	case 0x5ea: return pack_can_0x5ea_megasquirt_dash2(o, data);
	case 0x5eb: return pack_can_0x5eb_megasquirt_dash3(o, data);
	case 0x5ec: return pack_can_0x5ec_megasquirt_dash4(o, data);
	default: break; 
	}
	return -1; 
}

int message_dlc(const unsigned long id) {
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x5e8: return 8;
	case 0x5e9: return 8;
	case 0x5ea: return 8;
	case 0x5eb: return 8;
	case 0x5ec: return 8;
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_megasquirt_simplified_dash_broadcast_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x5e8: return print_can_0x5e8_megasquirt_dash0(o, output);
	case 0x5e9: return print_can_0x5e9_megasquirt_dash1(o, output);
	case 0x5ea: return print_can_0x5ea_megasquirt_dash2(o, output);
	case 0x5eb: return print_can_0x5eb_megasquirt_dash3(o, output);
	case 0x5ec: return print_can_0x5ec_megasquirt_dash4(o, output);
	default: break; 
	}
	return -1; 
}

